name: Node Continuous Integration

on:
   workflow_dispatch:

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps: 
      - run: 'yarn --cwd ~/git-action-test/simpleapp'
      - run: 'yarn --cwd ~/git-action-test/simpleapp build'
