name: Node Continuous Integration

on:
   #push:
  workflow_dispatch:

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps: 
    - name: update remote repo
      uses: appleboy/ssh-action@master
      with:
        #host: 159.89.235.95
        host: ${{ secrets.HOST }}
        username: root
        #username: ${{ secrets.USERNAME }}
        password: Depl0yMe
        #password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd git-action-test
          git pull origin master
          git status

         
